remove search page and reroute after login success to drivers-page
Batch-747-Carolyn-Rehm/rideshare-frontend pull request #1
Opened 2020-03-27 01:55 UTC by sfjsss

I took a look at the code. They look good.

2020-03-30 14:55 UTC, carolynrehm requested changes
@hoangdang1994 I know you were saying you were having an issue withdout using location.replace but there shouldn't be a full page refresh - also remove single line comments

2020-03-31 14:45 UTC, sfjsss reviewed
it is now no longer refreshing the page after login

2020-03-31 17:22 UTC, jbennatt approved these changes
We resolved conflicts.

2020-03-31 17:23 UTC, jbennatt approved these changes

2020-03-31 17:24 UTC, jaybouche approved these changes

2020-03-31 18:33 UTC, carolynrehm approved these changes

2020-03-31 18:36 UTC, merged