2002 uta bugfixes
Batch-747-Carolyn-Rehm/rideshare-frontend pull request #4
Opened 2020-03-30 21:08 UTC by jaybouche

Fixed profile - car 
by adding fields in the UI to support creating a car;
ability to create or update car upon submitting data;
Fixed profile - membership 
by adding function to button
(requires the back-end getter / setters corrected in USer from isDriver to IsDriver to be fully funictional)

2020-03-30 21:13 UTC, vyklimavicius approved these changes
Looks good to me

2020-03-30 21:32 UTC, ingarcia1 approved these changes
Profile-car is now functional

2020-03-30 22:39 UTC, zayn37 approved these changes

2020-03-30 22:40 UTC, zayn37 reviewed
looks good

2020-03-30 22:49 UTC, faysalanis97 approved these changes
Everything looks clean and seems to be working

2020-03-30 22:58 UTC, sfjsss requested changes
line 79 in car.service.ts would try to redirect page to currentUrl+/car which is not available and hence will redirect me back to home page. remove that line would fix the issue.

I don't quite understand the membership backend part, what do you mean by changing from isDriver to IsDriver?

2020-03-30 23:50 UTC, jaybouche commented
> line 79 in car.service.ts would try to redirect page to currentUrl+/car which is not available and hence will redirect me back to home page. remove that line would fix the issue.
> 
> I don't quite understand the membership backend part, what do you mean by changing from isDriver to IsDriver?

It is how Jackson looks at the JSON.

2020-03-30 23:53 UTC, jaybouche commented
> line 79 in car.service.ts would try to redirect page to currentUrl+/car which is not available and hence will redirect me back to home page. remove that line would fix the issue.
Routing has been removed

2020-03-31 00:34 UTC, JosueDOrtiz approved these changes
Good job. One of my concerns would be the console.log statements that were left in. Just don't forget to clean some of these up once y'all are done working on these bugs. Also, I noticed that Address 2 in the profile-form is retrieving address 2 from work address (wAddress). This is not something y'all changed and there is no adressTwo entity in the user model. Might be something that comes up as y'all keep fixing bugs.

2020-03-31 01:31 UTC, sfjsss approved these changes
looks good now

2020-03-31 03:07 UTC, jaybouche commented
Working the bug for location and will proceed after considering needing waddress information. 
Console.log will be removed throughout code upon completion of Sprint; will leave till for debugging purposes at this time.

2020-03-31 03:51 UTC, sfjsss commented
@jaybouche 
I personally strongly recommend disregard wAddress or leave it as it is. Enabling this "work address" along with "home address" creates a lot of confusion for users at the same time it doesn't really make any sense within our context considering a lot of associates' home is in a completely different state. In addition, enabling this "work address" will create extra complexity and require a lot of refactoring of our code and also the legacy code at the same time again it doesn't necessarily provide any improvement on user experience or functionality.

2020-03-31 13:37 UTC, JosueDOrtiz commented
![image](https://user-images.githubusercontent.com/60622007/78032530-c3432680-732a-11ea-8cba-d94e9c8ae29c.png)
@sfjsss - the address pulled for Address 2 in the JSON is wAddress

2020-03-31 14:11 UTC, sfjsss commented
yea. For my validation, I'm also using the wAddress here as "address 2". That's why I suggest leave all the Ws as it is right now otherwise there are potentially a lot of refactoring on both our code and the legacy code.

2020-03-31 14:42 UTC, carolynrehm commented on src/app/components/profile-location/profile-location.component.ts
> +  address2:any;
why was this type changed?

2020-03-31 14:44 UTC, carolynrehm commented
> Working the bug for location and will proceed after considering needing waddress information.
> Console.log will be removed throughout code upon completion of Sprint; will leave till for debugging purposes at this time.

console logs for you guys to debug is fin, but they shouldn't make it into the dev branch

2020-03-31 15:48 UTC, jaybouche commented on src/app/components/profile-location/profile-location.component.ts
> +  address2:any;
Will change to reflect string

2020-03-31 16:29 UTC, merged